import type { ManagedContent } from './types';

export const MOCK_MANAGED_CONTENTS: ManagedContent[] = [
  {
    id: 'content-1',
    title: 'BTS 뷔 솔로 앨범 소식 정리',
    category: 'K-POP',
    status: 'published',
    currentStep: 'published',
    language: 'es',
    views: 1840,
    updatedAt: '2026-04-29',
  },
  {
    id: 'content-2',
    title: '한국 로컬 여행 트렌드 소개',
    category: '문화',
    status: 'draft',
    currentStep: 'review_content',
    language: 'es',
    views: 320,
    updatedAt: '2026-04-28',
  },
  {
    id: 'content-3',
    title: 'K-푸드 매운맛 챌린지 카드뉴스',
    category: '음식',
    status: 'draft',
    currentStep: 'review_translation',
    language: 'es',
    views: 96,
    updatedAt: '2026-04-27',
  },
  {
    id: 'content-4',
    title: '신작 한국 드라마 관전 포인트',
    category: '드라마',
    status: 'draft',
    currentStep: 'preview',
    language: 'es',
    views: 740,
    updatedAt: '2026-04-26',
  },
  {
    id: 'content-5',
    title: '서울 패션위크 핵심 장면',
    category: '문화',
    status: 'draft',
    currentStep: 'preview',
    language: 'es',
    views: 1280,
    updatedAt: '2026-04-25',
  },
  {
    id: 'content-6',
    title: '한국어 표현으로 보는 팬덤 문화',
    category: '뉴스',
    status: 'draft',
    currentStep: 'select_article',
    language: 'es',
    views: 55,
    updatedAt: '2026-04-24',
  },
  {
    id: 'content-7',
    title: '뉴진스 빌보드 차트 진입 분석',
    category: 'K-POP',
    status: 'published',
    currentStep: 'published',
    language: 'es',
    views: 2560,
    updatedAt: '2026-04-23',
  },
  {
    id: 'content-8',
    title: '손흥민 시즌 기록 업데이트',
    category: '스포츠',
    status: 'published',
    currentStep: 'published',
    language: 'es',
    views: 980,
    updatedAt: '2026-04-22',
  },
];
